### PR TITLE
Match operations with permission objects with set operators

### PR DESCRIPTION
**Pull request by metatoaster**
Correct the operator terms to match what one might expect if they were working with permission objects as an encapsulation of sets of roles.

Test cases enclosed to demonstrate how this compares to working with the sets directly.

### CODE REVIEW

**Comment by ericcong** [comment]
This makes much more sense to me, is there a plan of merging this?

**Comment by indera** [comment]
This seems to be ready for a merge...

**Comment by mg-christian-axelsson** [comment]
I've created issue #110 and rebased this PR in #111 in hope of getting this merged. Would be nice not to have to maintain our own fork.

**Comment by Abdur-rahmaanJ** [comment]
Merged folks, thanks @mg-christian-axelsson 

If anybody wants to actively contribute, join the Pallets Discord and ping me at appinv

**Pull request closed without merging**
